import seedcase_sprout as sp

from .resource_properties_metabolic_rate import (
    resource_properties_metabolic_rate,
)

package_properties = sp.PackageProperties(
    ## Required:
    name="example-seed-beetle",
    title=(
        "Complex mitonuclear interactions and metabolic costs of mating "
        "in male seed beetles"
    ),
    description=(
        """
        Data from the 2015 on metabolic rate, respiratory quotient, body
        weight and ejaculate weight data from seed beetles with different
        mitonuclear genotypes.

        This repository shows how to use the Seedcase Sprout tools on a data set
        of seed beetle data. The data is from a study by [Immonen et al.
        (2015)](https://onlinelibrary.wiley.com/doi/10.1111/jeb.12789) and is
        available on [Zenodo](https://zenodo.org/records/4932381).
    """
    ),
    licenses=[
        sp.LicenseProperties(
            ## Required:
            name="CCO_1.0",
            ## Optional:
            path="https://creativecommons.org/publicdomain/zero/1.0/legalcode",
            title="CCO 1.0 UNIVERSAL",
        ),
    ],
    ## Optional:
    # homepage="",
    contributors=[
        # TODO: Considering to change role to "DataCollector" from datacite:
        # https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#7a-contributortype
        # Since they are not strictly the creators of this Data Package, but the
        sp.ContributorProperties(
            ## Required:
            title="Elina Immonen",
            ## Optional:
            path="https://www.uu.se/en/contact-and-organisation/staff?query=N12-1639",
            # creators of the data.
            roles=["creator"],
        ),
        sp.ContributorProperties(
            title="Johanna Liljestrand-Rönn",
            path="https://www.uu.se/en/contact-and-organisation/staff?query=N2-1345",
            roles=["creator"],
        ),
        sp.ContributorProperties(
            title="Christopher Watson",
            path="https://www.uu.se/en/department/ecology-and-genetics/research/evolutionary-biology/immonen-lab",
            roles=["creator"],
        ),
        sp.ContributorProperties(
            title="David Berger",
            path="https://www.uu.se/en/contact-and-organisation/staff?query=N11-2446",
            roles=["creator"],
        ),
        sp.ContributorProperties(
            title="Göran Arnqvist",
            path="https://www.uu.se/en/contact-and-organisation/staff?query=N1-1284",
            roles=["creator"],
        ),
    ],
    # keywords=[""],
    # image="",
    sources=[
        sp.SourceProperties(
            ## Required:
            title=(
                "Complex mitonuclear interactions and metabolic costs of mating "
                "in male seed beetles"
            ),
            ## Optional:
            path="https://zenodo.org/record/4932381",
            version="V1",
        ),
    ],
    resources=[
        resource_properties_metabolic_rate,
    ],
    ## Autogenerated:
    id="8dbef2a2-0354-4996-bc9e-71a6c79aec7d",
    version="0.1.0",
    created="2025-07-17T14:23:49+02:00",
)
